// All reusable variables here
#let myLang = "it"
#let myName = "Loris Libralato"
#let myMatricola = "2068237"
#let myTitle = "Titolo della tesi"
#let myDegree = "Tesi di laurea"
#let myUni = "Università degli studi di Padova"
#let myDepartment = "Dipartimento di Matematica ''Tullio Levi-Civita''"
#let myFaculty = "Corso di Laurea in Informatica"
#let profTitle = "Prof. "
#let myProf = "Nome Cognome"
#let myCompany = "Nome azienda"
#let myTutor = "Nome Cognome"
#let myLocation = "Padova"
#let myAA = "2024-2025"
#let myTime = "Giugno 2025"